### ISSUE TITLE
No longer allows block by reactions

### ISSUE THREAD

**Issue by queerterpreter** [gaeulbyul/RedBlock#13]
Since the last update, the block by reactions section is grayed out. I'm using Chrome.

**Comment by gaeulbyul** [comment]
Hello! When the block-by-reactions section is unavailable, probably it means...

1. Red Block's UI opened on the non-tweet webpage: Red Block detects tweet by browser's URL address(which should looks like `https://twitter.com/(username)/status/(tweet-id)` ). Would you try to open Red Block UI after navigating some tweet?
2. Or, Nobody RT/Liked on the given tweet (both retweeted count and liked count are zero)

Otherwise, please let me know more details about this bug. (ex. Is this bug occurs only in specific tweet or every tweets? /  Tweet's URL?)

**Comment by queerterpreter** [comment]
Oh, that's so strange! It was happening all day yesterday, even when I went to specific tweets (like how I used it up until now), but I just tried to reproduce it and it's no longer happening. Maybe there was some weirdness on my end and I was pending a restart. Thank you for getting back to me!
